
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("Dummy6.Resource", IsApplication=true)>]
    do ()

namespace Tasky.Droid.F
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnException5550caf741374619b7d4db2da5280791 of obj
    exception ReturnNoneException5550caf741374619b7d4db2da5280791
    [<AutoOpen>]
    module FuncConvertFinalOverload5550caf741374619b7d4db2da5280791 =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                global.Tasky.Core.Lib.Resource.String.library_name <- Resource_String.library_name


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member ic_action_addtask = 2130837504
            
            // aapt resource value: 0x7f020001
            static member ic_action_delete = 2130837505
            
            // aapt resource value: 0x7f020002
            static member ic_action_save = 2130837506
            
            // aapt resource value: 0x7f020003
            static member ic_checkmark = 2130837507
            
            // aapt resource value: 0x7f020004
            static member ic_launcher = 2130837508
            
            // aapt resource value: 0x7f020005
            static member monoandroidsplash = 2130837509
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f070002
            static member NameLabel = 2131165186
            
            // aapt resource value: 0x7f070004
            static member NotesLabel = 2131165188
            
            // aapt resource value: 0x7f070007
            static member checkMark = 2131165191
            
            // aapt resource value: 0x7f070009
            static member checkmark = 2131165193
            
            // aapt resource value: 0x7f070006
            static member chkDone = 2131165190
            
            // aapt resource value: 0x7f07000b
            static member lblDescription = 2131165195
            
            // aapt resource value: 0x7f07000a
            static member lblName = 2131165194
            
            // aapt resource value: 0x7f070008
            static member linearLayout1 = 2131165192
            
            // aapt resource value: 0x7f070000
            static member lstTasks = 2131165184
            
            // aapt resource value: 0x7f07000e
            static member menu_add_task = 2131165198
            
            // aapt resource value: 0x7f07000d
            static member menu_delete_task = 2131165197
            
            // aapt resource value: 0x7f07000c
            static member menu_save_task = 2131165196
            
            // aapt resource value: 0x7f070001
            static member myButton = 2131165185
            
            // aapt resource value: 0x7f070003
            static member txtName = 2131165187
            
            // aapt resource value: 0x7f070005
            static member txtNotes = 2131165189
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member HomeScreen = 2130903040
            
            // aapt resource value: 0x7f030001
            static member Main = 2130903041
            
            // aapt resource value: 0x7f030002
            static member TaskDetails = 2130903042
            
            // aapt resource value: 0x7f030003
            static member TaskListItem = 2130903043
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Menu () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f060000
            static member menu_detailsscreen = 2131099648
            
            // aapt resource value: 0x7f060001
            static member menu_homescreen = 2131099649
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040002
            static member app_name = 2130968578
            
            // aapt resource value: 0x7f040001
            static member hello = 2130968577
            
            // aapt resource value: 0x7f040000
            static member library_name = 2130968576
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Style () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050000
            static member Mono_Android_Theme_Splash = 2131034112
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

